#!/usr/bin/env bash

path=/home/mimi/Desktop/testing_Whenever
filename=output
streamer=$1

table="create table if not exists my_table ("
table+="id integer primary key autoincrement,"
table+="Run text,"
table+="Filtered text default 'No',"
table+="lane integer," 
table+="mid integer,"
table+="number_of_groups_analyzed integer default 0,"
table+="number_of_raw_groups integer default 0,"
table+="number_of_contaminations integer default 0,"
table+="a_to__ integer default 0,"
table+="a_to_c integer default 0,"
table+="a_to_g integer default 0,"
table+="a_to_t integer default 0,"
table+="c_to_a integer default 0,"
table+="c_to__ integer default 0,"
table+="c_to_g integer default 0,"
table+="c_to_t integer default 0,"
table+="g_to_a integer default 0,"
table+="g_to_c integer default 0,"
table+="g_to__ integer default 0,"
table+="g_to_t integer default 0,"
table+="t_to_a integer default 0,"
table+="t_to_c integer default 0,"
table+="t_to_g integer default 0,"
table+="t_to__ integer default 0," 
table+="__to_a integer default 0,"
table+="__to_c integer default 0,"
table+="__to_g integer default 0,"
table+="__to_t integer default 0,"
table+="other integer default 0,"
table+="hetero_a_to__ integer default 0,"
table+="hetero_a_to_c integer default 0,"
table+="hetero_a_to_g integer default 0,"
table+="hetero_a_to_t integer default 0,"
table+="hetero_c_to_a integer default 0,"
table+="hetero_c_to__ integer default 0," 
table+="hetero_c_to_g integer default 0,"
table+="hetero_c_to_t integer default 0,"
table+="hetero_g_to_a integer default 0,"
table+="hetero_g_to_c integer default 0," 
table+="hetero_g_to__ integer default 0,"
table+="hetero_g_to_t integer default 0," 
table+="hetero_t_to_a integer default 0,"
table+="hetero_t_to_c integer default 0,"
table+="hetero_t_to_g integer default 0,"
table+="hetero_t_to__ integer default 0,"
table+="hetero___to_a integer default 0,"
table+="hetero___to_c integer default 0,"
table+="hetero___to_g integer default 0,"
table+="hetero___to_t integer default 0,"
table+="hetero_other integer default 0)"

sqlite3 $filename.db << EOS
$table;
EOS

lane=
mid=
grps=
rowid=
function traverse() {   
	for file in $(ls "$1" | sort -n)
	do		
		if [[ -d ${1}/${file} ]]; then
			if [[ ${file} =~ lane_[0-9]+ ]]; then
				lane=${file##*_}			
			fi
			if [[ ${file} =~ ^[0-9]+$ ]]; then
				mid=${file}
				grps=0
			fi
			traverse "${1}/${file}"

		elif [[ ${1}/${file} =~ group[0-9]+.fna ]]  && ! [[ ${1}/${file} =~ con* ]]; then
			count=$(echo $(grep '>' ${1}/${file} | wc -l ))
			if (( "$count" >= 5 )); then
				echo $count${1}/${file}
				(( grps++ ))
			fi 

		elif [[ ${1}/${file} =~ output.txt ]]; then

sqlite3 $filename.db << EOS
			insert into my_table (Run, Filtered, lane, mid, number_of_groups_analyzed) values (date('now'), 'No', $lane, $mid, $grps);
EOS
			(( rowid++ ))
			./$streamer $filename.db ${1}/groupsizes.txt ${1}/${file} $rowid
		fi
	done
}

traverse $path
sqlite3 -header -csv $filename.db "select * from my_table;" > $filename.csv

exit 0
