#!/usr/bin/env bash

####################################################
# Specify your paths here:
#

#from_data_path=/home/mimi/Desktop/april_10/testing_Jan_2014/
from_data_path=/home/lykrysh/Data/testing_this/

#from_data_dirtype=jan2014 
#from_data_dirtype=mar2015
from_data_dirtype=other 

to_csv_path=${from_data_path::-1}_results/
to_csv_filename=output

#
####################################################

if [ "$#" -ne 1 ]; then
	echo "Usage: ./run scan"
	exit 0
fi

mkdir -p $to_csv_path

streamer=$1
source tabletocreate
sqlite3 $to_csv_path$to_csv_filename.db << EOS
$table;
EOS

lane=
mid=
grps=
rowid=

function traverse() {
	for file in $(ls "$1" | sort -V)
	do
		if [[ -d ${1}/${file} ]]; then
			case "$2" in
			jan2014)
				if [[ ${file} =~ [0-9]+_[0-9]+ ]]; then
					lane=${file##*_}
					mid=${file%_*}
					grps=0
				fi
				;;
			mar2015)
				if [[ ${file} =~ run[0-9]+ ]]; then
					lane=${file##*n}
				fi
				if [[ ${file} =~ [MID]?[0-9]+$ ]]; then
					mid=${file##*D}
					grps=0
				fi
				;;
			other)
				if [[ ${file} =~ lane_[0-9]+ ]]; then
					lane=${file##*_}
				fi
				if [[ ${file} =~ ^[0-9]+$ ]]; then
					mid=${file}
					grps=0
				fi
				;;
			*)	;;
			esac
			traverse "${1}/${file}" "$2"

		elif [[ ${1}/${file} =~ group[0-9]+.fna ]]  && ! [[ ${1}/${file} =~ con* ]]; then
			count=$(echo $(grep '>' ${1}/${file} | wc -l ))
			if (( "$count" >= 5 )); then
				#echo $count${1}/${file}
				(( grps++ ))
			fi 

		elif [[ ${1}/${file} =~ output.txt ]]; then

sqlite3 $to_csv_path$to_csv_filename.db << EOS
			insert into my_table (Run, Filtered, lane, mid, number_of_raw_groups) values (date('now'), 'No', $lane, $mid, $grps);
EOS
			(( rowid++ ))
			./$streamer $to_csv_path$to_csv_filename.db ${1}/${file} $rowid $grps
		fi
	done
}

traverse $from_data_path $from_data_dirtype
sqlite3 -header -csv $to_csv_path$to_csv_filename.db "select * from my_table;" > $to_csv_path$to_csv_filename.csv

exit 0
