#!/usr/bin/env bash

####################################################
# Specify your paths here:
#
from_data_path=/home/mimi/Desktop/april_10/testing_Jan_2014/
#from_data_path=/home/mimi/Desktop/testing_this/
to_csv_path=$(pwd)/examples/
to_csv_filename=output
#
####################################################

if [ "$#" -ne 1 ]; then
	echo "Usage: ./run scan"
	exit 0
fi

streamer=$1
source tabletocreate
sqlite3 $to_csv_path$to_csv_filename.db << EOS
$table;
EOS

lane=
mid=
grps=
rowid=
function traverse() {
	for file in $(ls "$1" | sort -n)
	do
		if [[ -d ${1}/${file} ]]; then
			if [[ ${file} =~ lane_[0-9]+ ]]; then
				lane=${file##*_}
			fi
			if [[ ${file} =~ ^[0-9]+$ ]]; then
				mid=${file}
				grps=0
			fi
			traverse "${1}/${file}"

		elif [[ ${1}/${file} =~ group[0-9]+.fna ]]  && ! [[ ${1}/${file} =~ con* ]]; then
			count=$(echo $(grep '>' ${1}/${file} | wc -l ))
			if (( "$count" >= 5 )); then
				#echo $count${1}/${file}
				(( grps++ ))
			fi 

		elif [[ ${1}/${file} =~ output.txt ]]; then

sqlite3 $to_csv_path$to_csv_filename.db << EOS
			insert into my_table (Run, Filtered, lane, mid, number_of_raw_groups) values (date('now'), 'No', $lane, $mid, $grps);
EOS
			(( rowid++ ))
			./$streamer $to_csv_path$to_csv_filename.db ${1}/${file} $rowid $grps
		fi
	done
}

traverse $from_data_path
sqlite3 -header -csv $to_csv_path$to_csv_filename.db "select * from my_table;" > $to_csv_path$to_csv_filename.csv

exit 0
