#!/usr/bin/env bash

####################################################
# Specify your paths here:
#

#from_data_path=/home/mimi/Desktop/april_10/testing_Jan_2014/
from_data_path=/home/lykrysh/Data/Jan_2014_jarek_processed/

from_data_dirtype=jan2014 
#from_data_dirtype=mar2015
#from_data_dirtype=other 

to_csv_path=${from_data_path::-1}_summary/

#
####################################################

if [[ ${1} =~ --with-no-* ]]; then
	to_csv_filename=unfiltered_$(date +"%Y%m%d")_$(date +"%H%M")
else
	to_csv_filename=filtered_$(date +"%Y%m%d")_$(date +"%H%M")
fi

mkdir -p $to_csv_path
sqlite3 $to_csv_path$to_csv_filename.db < sql/create_table

function scandir() {
	for file in $(ls "$1" | sort -V)
	do
		if [[ -d ${1}/${file} ]]; then
			case "$2" in
			jan2014)
				if [[ ${file} =~ [0-9]+_[0-9]+ ]]; then
					lane=${file##*_}
					mid=${file%_*}
					grps=0
				fi
				;;
			mar2015)
				if [[ ${file} =~ run[0-9]+ ]]; then
					lane=${file##*n}
				fi
				if [[ ${file} =~ [MID]?[0-9]+$ ]]; then
					mid=${file##*D}
					grps=0
				fi
				;;
			other)
				if [[ ${file} =~ lane_[0-9]+ ]]; then
					lane=${file##*_}
				fi
				if [[ ${file} =~ ^[0-9]+$ ]]; then
					mid=${file}
					grps=0
				fi
				;;
			*)	;;
			esac
			scandir "${1}/${file}" "$2"

		elif [[ ${1}/${file} =~ group[0-9]+.fna ]]  && ! [[ ${1}/${file} =~ con* ]]; then
			count=$(echo $(grep '>' ${1}/${file} | wc -l ))
			if (( "$count" >= 5 )); then
				#echo $count${1}/${file}
				(( grps++ ))
			fi 

		elif [[ ${1}/${file} =~ output.txt ]]; then
sqlite3 $to_csv_path$to_csv_filename.db << EOS
			insert into my_table (Run, Filtered, lane, mid, number_of_raw_groups) values (date('now'), 'No', $lane, $mid, $grps);
EOS
			(( rowid++ ))
			./scan $to_csv_path$to_csv_filename.db ${1}/${file} $rowid $grps >> ${to_csv_path}groups_with_true_mut
		fi
	done
}

scandir $from_data_path $from_data_dirtype
sqlite3 -header -csv $to_csv_path$to_csv_filename.db "select * from my_table;" > $to_csv_path$to_csv_filename.csv
rm -f $to_csv_path$to_csv_filename.db
exit 0
