#!/usr/bin/env bash

####################################################
# Specify your paths here:
#

from_data_path=/home/lykrysh/Data/march_2015/

from_data_dirtype=1 
#from_data_dirtype=2
#from_data_dirtype=3 

to_csv_path=${from_data_path::-1}_summary/

#
####################################################
timestamp=$(date +"%Y%m%d")_$(date +"%H%M")

if [[ ${1} =~ --with-no-* ]]; then
	to_csv_filename=unfiltered_$timestamp
else
	to_csv_filename=filtered_$timestamp
fi

mkdir -p $to_csv_path
sqlite3 $to_csv_path$to_csv_filename.db < sql/create_table

function scandir() {
	for file in $(ls "$1" | sort -V)
	do
		if [[ -d ${1}/${file} ]]; then
			case "$2" in
			1)
				if [[ ${file} =~ [0-9]+_[0-9]+ ]]; then
					lane=${file##*_}
					mid=${file%_*}
					grps=0
				fi
				;;
			2)
				if [[ ${file} =~ run[0-9]+ ]]; then
					lane=${file##*n}
				fi
				if [[ ${file} =~ [MID]?[0-9]+$ ]]; then
					mid=${file##*D}
					grps=0
				fi
				;;
			3)
				if [[ ${file} =~ lane_[0-9]+ ]]; then
					lane=${file##*_}
				fi
				if [[ ${file} =~ ^[0-9]+$ ]]; then
					mid=${file}
					grps=0
				fi
				;;
			*)	;;
			esac
			scandir "${1}/${file}" "$2"

		elif [[ ${1}/${file} =~ group[0-9]+.fna ]]  && ! [[ ${1}/${file} =~ con* ]]; then
			count=$(echo $(grep '>' ${1}/${file} | wc -l ))
			if (( "$count" >= 5 )); then
				#echo $count${1}/${file}
				(( grps++ ))
			fi 

		elif [[ ${1}/${file} =~ output.txt ]]; then
sqlite3 $to_csv_path$to_csv_filename.db << EOS
			insert into my_table ([data processed/analyzed], Filtered, lane, mid, [number of raw groups]) values (date('now'), 'No', $lane, $mid, $grps);
EOS
			(( rowid++ ))
			./scan $to_csv_path$to_csv_filename.db ${1}/${file} $rowid $grps >> ${to_csv_path}groups_with_true_mut_$timestamp
		fi
	done
}

scandir $from_data_path $from_data_dirtype
sqlite3 -header -csv $to_csv_path$to_csv_filename.db "select * from my_table;" > $to_csv_path$to_csv_filename.csv
rm -f $to_csv_path$to_csv_filename.db
exit 0
